inhibit_all_warnings!

target 'TBTweakViewController' do
  pod 'MirrorKit', :git => 'https://github.com/NSExceptional/MirrorKit.git', :branch => '2.0'
  pod 'TBAlertController'
  pod 'Masonry'
end

target 'TBTweakViewControllerTests' do

end

