inhibit_all_warnings!

target 'TBTweakViewController' do
  pod 'MirrorKit', :path => '../../../MirrorKit'
  pod 'TBAlertController'
  pod 'Masonry', :path => 'Pods/Masonry'
end

target 'TBTweakViewControllerTests' do

end

